/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Util;



/**
 *
 * @author Lucas
 */
public class JDlgClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgClientes
     */
    
    boolean pesquisando = false;
    
    public JDlgClientes(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setTitle("Cadastro de Clientes");
    setLocationRelativeTo(null);

    Util.habilitar(
        false, 
        jTxtCodCliente, 
        jTxtNomeCliente, 
        jTxtEmailCliente, 
        jFmtDataNascimentoCliente, 
        jFmtCpfCliente, 
        jFmtRgCliente, 
        jCboSexoCliente, 
        jTxtEnderecoCliente, 
        jFmtCepCliente, 
        jTxtBairroCliente, 
        jTxtCidadeCliente, 
        jChbAtivoCliente, 
        jFmtCelularCliente, 
        jFmtTelefoneCliente, 
        jTxtReferenciaCliente, 
        jBtnConfirmarCliente, 
        jBtnCancelarCliente
    );
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jComboBox2 = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLblCodCliente = new javax.swing.JLabel();
        jLblNomeCliente = new javax.swing.JLabel();
        jTxtNomeCliente = new javax.swing.JTextField();
        jTxtCodCliente = new javax.swing.JTextField();
        jLblCpfCliente = new javax.swing.JLabel();
        jLblRgCliente = new javax.swing.JLabel();
        jFmtCpfCliente = new javax.swing.JFormattedTextField();
        jFmtRgCliente = new javax.swing.JFormattedTextField();
        jLblSexoCliente = new javax.swing.JLabel();
        jCboSexoCliente = new javax.swing.JComboBox<>();
        jLblEmailCliente = new javax.swing.JLabel();
        jTxtEmailCliente = new javax.swing.JTextField();
        jLblDataNscmntCliente = new javax.swing.JLabel();
        jFmtDataNascimentoCliente = new javax.swing.JFormattedTextField();
        jLblCepCliente = new javax.swing.JLabel();
        jLblEnderecoCliente = new javax.swing.JLabel();
        jTxtEnderecoCliente = new javax.swing.JTextField();
        jLblBairroCliente = new javax.swing.JLabel();
        jTxtBairroCliente = new javax.swing.JTextField();
        jLblCidadeCliente = new javax.swing.JLabel();
        jTxtCidadeCliente = new javax.swing.JTextField();
        jFmtCepCliente = new javax.swing.JFormattedTextField();
        jLblCelularCliente = new javax.swing.JLabel();
        jFmtCelularCliente = new javax.swing.JFormattedTextField();
        jLblTelefoneCliente = new javax.swing.JLabel();
        jLblReferenciaCliente = new javax.swing.JLabel();
        jTxtReferenciaCliente = new javax.swing.JTextField();
        jFmtTelefoneCliente = new javax.swing.JFormattedTextField();
        jChbAtivoCliente = new javax.swing.JCheckBox();
        jBtnIncluirCliente = new javax.swing.JButton();
        jBtnAlterarCliente = new javax.swing.JButton();
        jBtnExcluirCliente = new javax.swing.JButton();
        jBtnConfirmarCliente = new javax.swing.JButton();
        jBtnCancelarCliente = new javax.swing.JButton();
        jBtnPesquisarCliente = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodCliente.setText("Código:");

        jLblNomeCliente.setText("Nome:");

        jLblCpfCliente.setText("Cpf:");

        jLblRgCliente.setText("Rg:");

        try {
            jFmtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtRgCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblSexoCliente.setText("Sexo:");

        jCboSexoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        jLblEmailCliente.setText("Email:");

        jTxtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailClienteActionPerformed(evt);
            }
        });

        jLblDataNscmntCliente.setText("Data de Nascimento:");

        try {
            jFmtDataNascimentoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblCepCliente.setText("Cep:");

        jLblEnderecoCliente.setText("Endereço:");

        jLblBairroCliente.setText("Bairro:");

        jLblCidadeCliente.setText("Cidade:");

        try {
            jFmtCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblCelularCliente.setText("Celular:");

        try {
            jFmtCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblTelefoneCliente.setText("Telefone:");

        jLblReferenciaCliente.setText("Referência:");

        try {
            jFmtTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtTelefoneClienteActionPerformed(evt);
            }
        });

        jChbAtivoCliente.setText("Ativo");
        jChbAtivoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivoClienteActionPerformed(evt);
            }
        });

        jBtnIncluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluirCliente.setText("Incluir");
        jBtnIncluirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnIncluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirClienteActionPerformed(evt);
            }
        });

        jBtnAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterarCliente.setText("Alterar");
        jBtnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarClienteActionPerformed(evt);
            }
        });

        jBtnExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluirCliente.setText("Excluir");
        jBtnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirClienteActionPerformed(evt);
            }
        });

        jBtnConfirmarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmarCliente.setText("Confirmar");
        jBtnConfirmarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarClienteActionPerformed(evt);
            }
        });

        jBtnCancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelarCliente.setText("Cancelar");
        jBtnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarClienteActionPerformed(evt);
            }
        });

        jBtnPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisarCliente.setText("Pesquisar");
        jBtnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCelularCliente)
                                .addGap(107, 107, 107)
                                .addComponent(jLblTelefoneCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCidadeCliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jChbAtivoCliente))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblNomeCliente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblCodCliente)
                                            .addComponent(jTxtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jFmtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFmtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLblSexoCliente)
                                                .addComponent(jCboSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLblEnderecoCliente)
                                                .addComponent(jLblBairroCliente))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLblCepCliente)
                                                .addComponent(jFmtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLblDataNscmntCliente)
                                                .addComponent(jFmtDataNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLblCpfCliente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLblRgCliente)
                                            .addGap(310, 310, 310))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jBtnPesquisarCliente)
                                        .addComponent(jBtnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jFmtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFmtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jBtnIncluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBtnConfirmarCliente))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jBtnCancelarCliente)
                                                .addComponent(jBtnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblReferenciaCliente)
                                        .addComponent(jTxtReferenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLblEmailCliente))))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmailCliente)
                    .addComponent(jLblDataNscmntCliente))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDataNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCpfCliente)
                    .addComponent(jLblRgCliente)
                    .addComponent(jLblSexoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEnderecoCliente)
                    .addComponent(jLblCepCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCidadeCliente)
                    .addComponent(jLblBairroCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCelularCliente)
                    .addComponent(jLblTelefoneCliente)
                    .addComponent(jLblReferenciaCliente))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtReferenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFmtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnExcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirClienteActionPerformed
        // TODO add your handling code here:
       Util.habilitar(true, jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente, jBtnConfirmarCliente, jBtnCancelarCliente);
       Util.habilitar(false, jBtnIncluirCliente, jBtnAlterarCliente, jBtnExcluirCliente, jBtnPesquisarCliente);
       Util.limpar(jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente);  

    }//GEN-LAST:event_jBtnIncluirClienteActionPerformed

    private void jBtnConfirmarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarClienteActionPerformed
        // TODO add your handling code here:
       Util.habilitar(false, jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente, jBtnConfirmarCliente, jBtnCancelarCliente);
       Util.habilitar(true, jBtnIncluirCliente, jBtnAlterarCliente, jBtnExcluirCliente, jBtnPesquisarCliente);
       Util.limpar(jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente);  
                       
    }//GEN-LAST:event_jBtnConfirmarClienteActionPerformed

    private void jChbAtivoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivoClienteActionPerformed

    private void jBtnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirClienteActionPerformed
        // TODO add your handling code here:
       if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar um usuário primeiro");
        } else {
                Util.perguntar("Você deseja excluir?");
                Util.limpar(jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente);  
        } 

    }//GEN-LAST:event_jBtnExcluirClienteActionPerformed

    private void jBtnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarClienteActionPerformed
        // TODO add your handling code here:
       Util.habilitar(false, jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente, jBtnConfirmarCliente, jBtnCancelarCliente);
       Util.habilitar(true, jBtnIncluirCliente, jBtnAlterarCliente, jBtnExcluirCliente, jBtnPesquisarCliente);
       Util.limpar(jTxtCodCliente, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente);  

    }//GEN-LAST:event_jBtnCancelarClienteActionPerformed

    private void jBtnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarClienteActionPerformed
        // TODO add your handling code here:
       Util.habilitar(true, jTxtNomeCliente, jTxtEmailCliente, jFmtDataNascimentoCliente, jFmtCpfCliente, jFmtRgCliente, jCboSexoCliente, jTxtEnderecoCliente, jFmtCepCliente, jTxtBairroCliente, jTxtCidadeCliente, jChbAtivoCliente, jFmtCelularCliente, jFmtTelefoneCliente, jTxtReferenciaCliente, jBtnConfirmarCliente, jBtnCancelarCliente);
       Util.habilitar(false, jBtnIncluirCliente, jBtnAlterarCliente, jBtnExcluirCliente, jBtnPesquisarCliente);
    }//GEN-LAST:event_jBtnAlterarClienteActionPerformed

    private void jBtnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarClienteActionPerformed
        // TODO add your handling code here:
        //pesquisa = true;
        JDlgClientePesquisar jDlgClientePesquisar = new JDlgClientePesquisar(null, true);
        jDlgClientePesquisar.setTelaPai(this);
        jDlgClientePesquisar.setVisible(true);
        pesquisando = true;
    }//GEN-LAST:event_jBtnPesquisarClienteActionPerformed

    private void jFmtTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtTelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtTelefoneClienteActionPerformed

    private void jTxtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JDlgClientes dialog = new JDlgClientes(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBtnAlterarCliente;
    private javax.swing.JButton jBtnCancelarCliente;
    private javax.swing.JButton jBtnConfirmarCliente;
    private javax.swing.JButton jBtnExcluirCliente;
    private javax.swing.JButton jBtnIncluirCliente;
    private javax.swing.JButton jBtnPesquisarCliente;
    private javax.swing.JComboBox<String> jCboSexoCliente;
    private javax.swing.JCheckBox jChbAtivoCliente;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFmtCelularCliente;
    private javax.swing.JFormattedTextField jFmtCepCliente;
    private javax.swing.JFormattedTextField jFmtCpfCliente;
    private javax.swing.JFormattedTextField jFmtDataNascimentoCliente;
    private javax.swing.JFormattedTextField jFmtRgCliente;
    private javax.swing.JFormattedTextField jFmtTelefoneCliente;
    private javax.swing.JLabel jLblBairroCliente;
    private javax.swing.JLabel jLblCelularCliente;
    private javax.swing.JLabel jLblCepCliente;
    private javax.swing.JLabel jLblCidadeCliente;
    private javax.swing.JLabel jLblCodCliente;
    private javax.swing.JLabel jLblCpfCliente;
    private javax.swing.JLabel jLblDataNscmntCliente;
    private javax.swing.JLabel jLblEmailCliente;
    private javax.swing.JLabel jLblEnderecoCliente;
    private javax.swing.JLabel jLblNomeCliente;
    private javax.swing.JLabel jLblReferenciaCliente;
    private javax.swing.JLabel jLblRgCliente;
    private javax.swing.JLabel jLblSexoCliente;
    private javax.swing.JLabel jLblTelefoneCliente;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTxtBairroCliente;
    private javax.swing.JTextField jTxtCidadeCliente;
    private javax.swing.JTextField jTxtCodCliente;
    private javax.swing.JTextField jTxtEmailCliente;
    private javax.swing.JTextField jTxtEnderecoCliente;
    private javax.swing.JTextField jTxtNomeCliente;
    private javax.swing.JTextField jTxtReferenciaCliente;
    // End of variables declaration//GEN-END:variables

}
