/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Util;


/**
 *
 * @author Lucas
 */
public class JDlgVendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVendedor
     */
    
    public JDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro Vendedor");
        setLocationRelativeTo(null);
        
        Util.habilitar(false, jTxtCodVendedor, jTxtNomeVendedor, jTxtEmailVendedor, jFmtCpfVendedor, jCboSexoVendedor, jFmtCelularVendedor, jTxtCidadeVendedor, jBtnConfirmarVendedor, jBtnCancelarVendedor);        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCodVendedor = new javax.swing.JLabel();
        jTxtCodVendedor = new javax.swing.JTextField();
        jLblNomeVendedor = new javax.swing.JLabel();
        jTxtNomeVendedor = new javax.swing.JTextField();
        jLblEmailVendedor = new javax.swing.JLabel();
        jTxtEmailVendedor = new javax.swing.JTextField();
        jLblSexoVendedor = new javax.swing.JLabel();
        jCboSexoVendedor = new javax.swing.JComboBox<>();
        jLblCpfVendedor = new javax.swing.JLabel();
        jLblCelularVendedor = new javax.swing.JLabel();
        jFmtCpfVendedor = new javax.swing.JFormattedTextField();
        jFmtCelularVendedor = new javax.swing.JFormattedTextField();
        jLblCidadeVendedor = new javax.swing.JLabel();
        jBtnIncluirVendedor = new javax.swing.JButton();
        jBtnAlterarVendedor = new javax.swing.JButton();
        jBtnExcluirVendedor = new javax.swing.JButton();
        jBtnConfirmarVendedor = new javax.swing.JButton();
        jBtnCancelarVendedor = new javax.swing.JButton();
        jBtnPesquisarVendedor = new javax.swing.JButton();
        jTxtCidadeVendedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodVendedor.setText("Código do Vendedor:");

        jTxtCodVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodVendedorActionPerformed(evt);
            }
        });

        jLblNomeVendedor.setText("Nome:");

        jLblEmailVendedor.setText("Email:");

        jLblSexoVendedor.setText("Sexo:");

        jCboSexoVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        jLblCpfVendedor.setText("Cpf:");

        jLblCelularVendedor.setText("Celular:");

        try {
            jFmtCpfVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtCelularVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblCidadeVendedor.setText("Cidade:");

        jBtnIncluirVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluirVendedor.setText("Incluir");
        jBtnIncluirVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirVendedorActionPerformed(evt);
            }
        });

        jBtnAlterarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterarVendedor.setText("Alterar");
        jBtnAlterarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarVendedorActionPerformed(evt);
            }
        });

        jBtnExcluirVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluirVendedor.setText("Excluir");
        jBtnExcluirVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirVendedorActionPerformed(evt);
            }
        });

        jBtnConfirmarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmarVendedor.setText("Confirmar");
        jBtnConfirmarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarVendedorActionPerformed(evt);
            }
        });

        jBtnCancelarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelarVendedor.setText("Cancelar");
        jBtnCancelarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarVendedorActionPerformed(evt);
            }
        });

        jBtnPesquisarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisarVendedor.setText("Pesquisar");
        jBtnPesquisarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCodVendedor)
                    .addComponent(jTxtNomeVendedor)
                    .addComponent(jTxtEmailVendedor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFmtCelularVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jFmtCpfVendedor))
                            .addComponent(jLblCelularVendedor)
                            .addComponent(jLblCodVendedor)
                            .addComponent(jLblNomeVendedor)
                            .addComponent(jLblCpfVendedor)
                            .addComponent(jLblEmailVendedor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCboSexoVendedor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblSexoVendedor)
                                    .addComponent(jLblCidadeVendedor))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtCidadeVendedor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnIncluirVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnConfirmarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnAlterarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnCancelarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnPesquisarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnExcluirVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNomeVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblEmailVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtEmailVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCpfVendedor)
                    .addComponent(jLblSexoVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboSexoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCelularVendedor)
                    .addComponent(jLblCidadeVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCidadeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluirVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnExcluirVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAlterarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmarVendedor)
                        .addComponent(jBtnCancelarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnPesquisarVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodVendedorActionPerformed

    private void jBtnIncluirVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirVendedorActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtCodVendedor, jTxtNomeVendedor, jTxtEmailVendedor, jFmtCpfVendedor, jCboSexoVendedor, jFmtCelularVendedor, jTxtCidadeVendedor, jBtnConfirmarVendedor, jBtnCancelarVendedor);
        Util.habilitar(false, jBtnIncluirVendedor, jBtnAlterarVendedor, jBtnExcluirVendedor, jBtnPesquisarVendedor);
    }//GEN-LAST:event_jBtnIncluirVendedorActionPerformed

    private void jBtnCancelarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarVendedorActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCodVendedor, jTxtNomeVendedor, jTxtEmailVendedor, jFmtCpfVendedor, jCboSexoVendedor, jFmtCelularVendedor, jTxtCidadeVendedor, jBtnConfirmarVendedor, jBtnCancelarVendedor);
        Util.habilitar(true, jBtnIncluirVendedor, jBtnAlterarVendedor, jBtnExcluirVendedor, jBtnPesquisarVendedor);
    }//GEN-LAST:event_jBtnCancelarVendedorActionPerformed

    private void jBtnConfirmarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarVendedorActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCodVendedor, jTxtNomeVendedor, jTxtEmailVendedor, jFmtCpfVendedor, jCboSexoVendedor, jFmtCelularVendedor, jTxtCidadeVendedor, jBtnConfirmarVendedor, jBtnCancelarVendedor);
        Util.habilitar(true, jBtnIncluirVendedor, jBtnAlterarVendedor, jBtnExcluirVendedor, jBtnPesquisarVendedor);
    }//GEN-LAST:event_jBtnConfirmarVendedorActionPerformed

    private void jBtnExcluirVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirVendedorActionPerformed
        // TODO add your handling code here:
        Util.perguntar("Deseja excluir o registro?");
    }//GEN-LAST:event_jBtnExcluirVendedorActionPerformed

    private void jBtnAlterarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarVendedorActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtNomeVendedor, jTxtEmailVendedor, jFmtCpfVendedor, jCboSexoVendedor, jFmtCelularVendedor, jTxtCidadeVendedor, jBtnConfirmarVendedor, jBtnCancelarVendedor);
        Util.habilitar(false, jBtnIncluirVendedor, jBtnAlterarVendedor, jBtnExcluirVendedor, jBtnPesquisarVendedor);
    }//GEN-LAST:event_jBtnAlterarVendedorActionPerformed

    private void jBtnPesquisarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarVendedorActionPerformed
        // TODO add your handling code here:
        //pesquisa = true;
        JDlgVendedorPesquisar jDlgVendedorPesquisar = new JDlgVendedorPesquisar(null, true);
        jDlgVendedorPesquisar.setTelaPai(this);
        jDlgVendedorPesquisar.setVisible(true);
        
    }//GEN-LAST:event_jBtnPesquisarVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JDlgVendedor dialog = new JDlgVendedor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterarVendedor;
    private javax.swing.JButton jBtnCancelarVendedor;
    private javax.swing.JButton jBtnConfirmarVendedor;
    private javax.swing.JButton jBtnExcluirVendedor;
    private javax.swing.JButton jBtnIncluirVendedor;
    private javax.swing.JButton jBtnPesquisarVendedor;
    private javax.swing.JComboBox<String> jCboSexoVendedor;
    private javax.swing.JFormattedTextField jFmtCelularVendedor;
    private javax.swing.JFormattedTextField jFmtCpfVendedor;
    private javax.swing.JLabel jLblCelularVendedor;
    private javax.swing.JLabel jLblCidadeVendedor;
    private javax.swing.JLabel jLblCodVendedor;
    private javax.swing.JLabel jLblCpfVendedor;
    private javax.swing.JLabel jLblEmailVendedor;
    private javax.swing.JLabel jLblNomeVendedor;
    private javax.swing.JLabel jLblSexoVendedor;
    private javax.swing.JTextField jTxtCidadeVendedor;
    private javax.swing.JTextField jTxtCodVendedor;
    private javax.swing.JTextField jTxtEmailVendedor;
    private javax.swing.JTextField jTxtNomeVendedor;
    // End of variables declaration//GEN-END:variables

}
