package bean;
// Generated 06/10/2025 19:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LltCliente generated by hbm2java
 */
@Entity
@Table(name="llt_cliente"
    ,catalog="db_lucas_thiel"
)
public class LltCliente  implements java.io.Serializable {


     private int lltIdCliente;
     private String lltNome;
     private String lltCpf;
     private String lltRg;
     private String lltSexo;
     private Date lltDataNascimento;
     private String lltEmail;
     private String lltCep;
     private String lltEndereco;
     private String lltBairro;
     private String lltCidade;
     private String lltTelefoneResidencial;
     private String lltCelular;
     private String lltReferencia;
     private String lltAtivo;

    public LltCliente() {
    }

	
    public LltCliente(int lltIdCliente, String lltNome, String lltCpf, String lltRg, String lltEmail, String lltCep, String lltEndereco, String lltBairro, String lltCidade, String lltCelular) {
        this.lltIdCliente = lltIdCliente;
        this.lltNome = lltNome;
        this.lltCpf = lltCpf;
        this.lltRg = lltRg;
        this.lltEmail = lltEmail;
        this.lltCep = lltCep;
        this.lltEndereco = lltEndereco;
        this.lltBairro = lltBairro;
        this.lltCidade = lltCidade;
        this.lltCelular = lltCelular;
    }
    public LltCliente(int lltIdCliente, String lltNome, String lltCpf, String lltRg, String lltSexo, Date lltDataNascimento, String lltEmail, String lltCep, String lltEndereco, String lltBairro, String lltCidade, String lltTelefoneResidencial, String lltCelular, String lltReferencia, String lltAtivo) {
       this.lltIdCliente = lltIdCliente;
       this.lltNome = lltNome;
       this.lltCpf = lltCpf;
       this.lltRg = lltRg;
       this.lltSexo = lltSexo;
       this.lltDataNascimento = lltDataNascimento;
       this.lltEmail = lltEmail;
       this.lltCep = lltCep;
       this.lltEndereco = lltEndereco;
       this.lltBairro = lltBairro;
       this.lltCidade = lltCidade;
       this.lltTelefoneResidencial = lltTelefoneResidencial;
       this.lltCelular = lltCelular;
       this.lltReferencia = lltReferencia;
       this.lltAtivo = lltAtivo;
    }
   
     @Id 

    
    @Column(name="llt_idCliente", unique=true, nullable=false)
    public int getLltIdCliente() {
        return this.lltIdCliente;
    }
    
    public void setLltIdCliente(int lltIdCliente) {
        this.lltIdCliente = lltIdCliente;
    }

    
    @Column(name="llt_nome", nullable=false, length=100)
    public String getLltNome() {
        return this.lltNome;
    }
    
    public void setLltNome(String lltNome) {
        this.lltNome = lltNome;
    }

    
    @Column(name="llt_cpf", nullable=false, length=14)
    public String getLltCpf() {
        return this.lltCpf;
    }
    
    public void setLltCpf(String lltCpf) {
        this.lltCpf = lltCpf;
    }

    
    @Column(name="llt_rg", nullable=false, length=10)
    public String getLltRg() {
        return this.lltRg;
    }
    
    public void setLltRg(String lltRg) {
        this.lltRg = lltRg;
    }

    
    @Column(name="llt_sexo", length=1)
    public String getLltSexo() {
        return this.lltSexo;
    }
    
    public void setLltSexo(String lltSexo) {
        this.lltSexo = lltSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="llt_dataNascimento", length=10)
    public Date getLltDataNascimento() {
        return this.lltDataNascimento;
    }
    
    public void setLltDataNascimento(Date lltDataNascimento) {
        this.lltDataNascimento = lltDataNascimento;
    }

    
    @Column(name="llt_email", nullable=false, length=80)
    public String getLltEmail() {
        return this.lltEmail;
    }
    
    public void setLltEmail(String lltEmail) {
        this.lltEmail = lltEmail;
    }

    
    @Column(name="llt_cep", nullable=false, length=9)
    public String getLltCep() {
        return this.lltCep;
    }
    
    public void setLltCep(String lltCep) {
        this.lltCep = lltCep;
    }

    
    @Column(name="llt_endereco", nullable=false, length=50)
    public String getLltEndereco() {
        return this.lltEndereco;
    }
    
    public void setLltEndereco(String lltEndereco) {
        this.lltEndereco = lltEndereco;
    }

    
    @Column(name="llt_bairro", nullable=false, length=30)
    public String getLltBairro() {
        return this.lltBairro;
    }
    
    public void setLltBairro(String lltBairro) {
        this.lltBairro = lltBairro;
    }

    
    @Column(name="llt_cidade", nullable=false, length=50)
    public String getLltCidade() {
        return this.lltCidade;
    }
    
    public void setLltCidade(String lltCidade) {
        this.lltCidade = lltCidade;
    }

    
    @Column(name="llt_telefoneResidencial", length=18)
    public String getLltTelefoneResidencial() {
        return this.lltTelefoneResidencial;
    }
    
    public void setLltTelefoneResidencial(String lltTelefoneResidencial) {
        this.lltTelefoneResidencial = lltTelefoneResidencial;
    }

    
    @Column(name="llt_celular", nullable=false, length=18)
    public String getLltCelular() {
        return this.lltCelular;
    }
    
    public void setLltCelular(String lltCelular) {
        this.lltCelular = lltCelular;
    }

    
    @Column(name="llt_referencia", length=150)
    public String getLltReferencia() {
        return this.lltReferencia;
    }
    
    public void setLltReferencia(String lltReferencia) {
        this.lltReferencia = lltReferencia;
    }

    
    @Column(name="llt_ativo", length=1)
    public String getLltAtivo() {
        return this.lltAtivo;
    }
    
    public void setLltAtivo(String lltAtivo) {
        this.lltAtivo = lltAtivo;
    }




}


