package bean;
// Generated 06/10/2025 19:07:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LltProduto generated by hbm2java
 */
@Entity
@Table(name="llt_produto"
    ,catalog="db_lucas_thiel"
)
public class LltProduto  implements java.io.Serializable {


     private int lltIdProduto;
     private String lltNomeProduto;
     private String lltMarca;
     private String lltTamanho;
     private String lltCategoria;
     private String lltCor;
     private double lltPreco;

    public LltProduto() {
    }

    public LltProduto(int lltIdProduto, String lltNomeProduto, String lltMarca, String lltTamanho, String lltCategoria, String lltCor, double lltPreco) {
       this.lltIdProduto = lltIdProduto;
       this.lltNomeProduto = lltNomeProduto;
       this.lltMarca = lltMarca;
       this.lltTamanho = lltTamanho;
       this.lltCategoria = lltCategoria;
       this.lltCor = lltCor;
       this.lltPreco = lltPreco;
    }
   
     @Id 

    
    @Column(name="llt_idProduto", unique=true, nullable=false)
    public int getLltIdProduto() {
        return this.lltIdProduto;
    }
    
    public void setLltIdProduto(int lltIdProduto) {
        this.lltIdProduto = lltIdProduto;
    }

    
    @Column(name="llt_nomeProduto", nullable=false, length=100)
    public String getLltNomeProduto() {
        return this.lltNomeProduto;
    }
    
    public void setLltNomeProduto(String lltNomeProduto) {
        this.lltNomeProduto = lltNomeProduto;
    }

    
    @Column(name="llt_marca", nullable=false, length=20)
    public String getLltMarca() {
        return this.lltMarca;
    }
    
    public void setLltMarca(String lltMarca) {
        this.lltMarca = lltMarca;
    }

    
    @Column(name="llt_tamanho", nullable=false, length=4)
    public String getLltTamanho() {
        return this.lltTamanho;
    }
    
    public void setLltTamanho(String lltTamanho) {
        this.lltTamanho = lltTamanho;
    }

    
    @Column(name="llt_categoria", nullable=false, length=50)
    public String getLltCategoria() {
        return this.lltCategoria;
    }
    
    public void setLltCategoria(String lltCategoria) {
        this.lltCategoria = lltCategoria;
    }

    
    @Column(name="llt_cor", nullable=false, length=30)
    public String getLltCor() {
        return this.lltCor;
    }
    
    public void setLltCor(String lltCor) {
        this.lltCor = lltCor;
    }

    
    @Column(name="llt_preco", nullable=false, precision=10)

    public double getLltPreco() {
        return this.lltPreco;
    }
    
    public void setLltPreco(double lltPreco) {
        this.lltPreco = lltPreco;
    }





}


