package bean;
// Generated 06/10/2025 19:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LltUsuario generated by hbm2java
 */
@Entity
@Table(name="llt_usuario"
    ,catalog="db_lucas_thiel"
)
public class LltUsuario  implements java.io.Serializable {


     private int lltIdUsuario;
     private String lltNome;
     private String lltApelido;
     private String lltCpf;
     private Date lltDataNascimento;
     private String lltSenha;
     private int lltNivel;
     private String lltAtivo;

    public LltUsuario() {
    }

    public LltUsuario(int lltIdUsuario, String lltNome, String lltApelido, String lltCpf, Date lltDataNascimento, String lltSenha, int lltNivel, String lltAtivo) {
       this.lltIdUsuario = lltIdUsuario;
       this.lltNome = lltNome;
       this.lltApelido = lltApelido;
       this.lltCpf = lltCpf;
       this.lltDataNascimento = lltDataNascimento;
       this.lltSenha = lltSenha;
       this.lltNivel = lltNivel;
       this.lltAtivo = lltAtivo;
    }
   
     @Id

    
    @Column(name="llt_idUsuario", unique=true, nullable=false)
    public int getLltIdUsuario() {
        return this.lltIdUsuario;
    }
    
    public void setLltIdUsuario(int lltIdUsuario) {
        this.lltIdUsuario = lltIdUsuario;
    }

    
    @Column(name="llt_nome", nullable=false, length=50)
    public String getLltNome() {
        return this.lltNome;
    }
    
    public void setLltNome(String lltNome) {
        this.lltNome = lltNome;
    }

    
    @Column(name="llt_apelido", nullable=false, length=25)
    public String getLltApelido() {
        return this.lltApelido;
    }
    
    public void setLltApelido(String lltApelido) {
        this.lltApelido = lltApelido;
    }

    
    @Column(name="llt_cpf", nullable=false, length=14)
    public String getLltCpf() {
        return this.lltCpf;
    }
    
    public void setLltCpf(String lltCpf) {
        this.lltCpf = lltCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="llt_dataNascimento", nullable=false, length=10)
    public Date getLltDataNascimento() {
        return this.lltDataNascimento;
    }
    
    public void setLltDataNascimento(Date lltDataNascimento) {
        this.lltDataNascimento = lltDataNascimento;
    }

    
    @Column(name="llt_senha", nullable=false, length=20)
    public String getLltSenha() {
        return this.lltSenha;
    }
    
    public void setLltSenha(String lltSenha) {
        this.lltSenha = lltSenha;
    }

    
    @Column(name="llt_nivel", nullable=false)
    public int getLltNivel() {
        return this.lltNivel;
    }
    
    public void setLltNivel(int lltNivel) {
        this.lltNivel = lltNivel;
    }

    
    @Column(name="llt_ativo", nullable=false, length=1)
    public String getLltAtivo() {
        return this.lltAtivo;
    }
    
    public void setLltAtivo(String lltAtivo) {
        this.lltAtivo = lltAtivo;
    }




}


