package bean;
// Generated 06/10/2025 19:07:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LltVendaProduto generated by hbm2java
 */
@Entity
@Table(name="llt_venda_produto"
    ,catalog="db_lucas_thiel"
)
public class LltVendaProduto  implements java.io.Serializable {


     private int lltIdVendaProduto;
     private int lltIdVenda;
     private int lltIdProduto;
     private int lltQuantidade;
     private double lltValorUnitario;
     private String lltStatusVenda;
     private String lltTipoEmbalagem;

    public LltVendaProduto() {
    }

    public LltVendaProduto(int lltIdVenda, int lltIdProduto, int lltQuantidade, double lltValorUnitario, String lltStatusVenda, String lltTipoEmbalagem) {
       this.lltIdVenda = lltIdVenda;
       this.lltIdProduto = lltIdProduto;
       this.lltQuantidade = lltQuantidade;
       this.lltValorUnitario = lltValorUnitario;
       this.lltStatusVenda = lltStatusVenda;
       this.lltTipoEmbalagem = lltTipoEmbalagem;
    }
   
     @Id 

    
    @Column(name="llt_idVendaProduto", unique=true, nullable=false)
    public int getLltIdVendaProduto() {
        return this.lltIdVendaProduto;
    }
    
    public void setLltIdVendaProduto(int lltIdVendaProduto) {
        this.lltIdVendaProduto = lltIdVendaProduto;
    }

    
    @Column(name="llt_idVenda", nullable=false)
    public int getLltIdVenda() {
        return this.lltIdVenda;
    }
    
    public void setLltIdVenda(int lltIdVenda) {
        this.lltIdVenda = lltIdVenda;
    }

    
    @Column(name="llt_idProduto", nullable=false)
    public int getLltIdProduto() {
        return this.lltIdProduto;
    }
    
    public void setLltIdProduto(int lltIdProduto) {
        this.lltIdProduto = lltIdProduto;
    }

    
    @Column(name="llt_quantidade", nullable=false)
    public int getLltQuantidade() {
        return this.lltQuantidade;
    }
    
    public void setLltQuantidade(int lltQuantidade) {
        this.lltQuantidade = lltQuantidade;
    }

    
    @Column(name="llt_valorUnitario", nullable=false, precision=10)
    public double getLltValorUnitario() {
        return this.lltValorUnitario;
    }
    
    public void setLltValorUnitario(double lltValorUnitario) {
        this.lltValorUnitario = lltValorUnitario;
    }

    
    @Column(name="llt_statusVenda", nullable=false, length=15)
    public String getLltStatusVenda() {
        return this.lltStatusVenda;
    }
    
    public void setLltStatusVenda(String lltStatusVenda) {
        this.lltStatusVenda = lltStatusVenda;
    }

    
    @Column(name="llt_tipoEmbalagem", nullable=false, length=25)
    public String getLltTipoEmbalagem() {
        return this.lltTipoEmbalagem;
    }
    
    public void setLltTipoEmbalagem(String lltTipoEmbalagem) {
        this.lltTipoEmbalagem = lltTipoEmbalagem;
    }




}


