package bean;
// Generated 06/10/2025 19:07:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LltVendedor generated by hbm2java
 */
@Entity
@Table(name="llt_vendedor"
    ,catalog="db_lucas_thiel"
)
public class LltVendedor  implements java.io.Serializable {


     private int lltIdVendedor;
     private String lltNome;
     private String lltCelular;
     private String lltEmail;
     private String lltSexo;
     private String lltCpf;
     private String lltCidade;

    public LltVendedor() {
    }

    public LltVendedor(int lltIdVendedor, String lltNome, String lltCelular, String lltEmail, String lltSexo, String lltCpf, String lltCidade) {
       this.lltIdVendedor = lltIdVendedor;
       this.lltNome = lltNome;
       this.lltCelular = lltCelular;
       this.lltEmail = lltEmail;
       this.lltSexo = lltSexo;
       this.lltCpf = lltCpf;
       this.lltCidade = lltCidade;
    }
   
     @Id 

    
    @Column(name="llt_idVendedor", unique=true, nullable=false)
    public int getLltIdVendedor() {
        return this.lltIdVendedor;
    }
    
    public void setLltIdVendedor(int lltIdVendedor) {
        this.lltIdVendedor = lltIdVendedor;
    }

    
    @Column(name="llt_nome", nullable=false, length=100)
    public String getLltNome() {
        return this.lltNome;
    }
    
    public void setLltNome(String lltNome) {
        this.lltNome = lltNome;
    }

    
    @Column(name="llt_celular", nullable=false, length=18)
    public String getLltCelular() {
        return this.lltCelular;
    }
    
    public void setLltCelular(String lltCelular) {
        this.lltCelular = lltCelular;
    }

    
    @Column(name="llt_email", nullable=false, length=80)
    public String getLltEmail() {
        return this.lltEmail;
    }
    
    public void setLltEmail(String lltEmail) {
        this.lltEmail = lltEmail;
    }

    
    @Column(name="llt_sexo", nullable=false, length=1)
    public String getLltSexo() {
        return this.lltSexo;
    }
    
    public void setLltSexo(String lltSexo) {
        this.lltSexo = lltSexo;
    }

    
    @Column(name="llt_cpf", nullable=false, length=14)
    public String getLltCpf() {
        return this.lltCpf;
    }
    
    public void setLltCpf(String lltCpf) {
        this.lltCpf = lltCpf;
    }

    
    @Column(name="llt_cidade", nullable=false, length=50)
    public String getLltCidade() {
        return this.lltCidade;
    }
    
    public void setLltCidade(String lltCidade) {
        this.lltCidade = lltCidade;
    }
    
    @Override
    public String toString() {
        return this.lltNome;
    }

    @Override
    public boolean equals( Object object){
        if(object instanceof LltVendedor) {
            LltVendedor lltVendedor = (LltVendedor)object;
            if(this.getLltIdVendedor()== lltVendedor.getLltIdVendedor()){
                return true;
            }
    }

        return false;
    }


}


