package bean;
// Generated 06/10/2025 19:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LltVenda generated by hbm2java
 */
@Entity
@Table(name="llt_venda"
    ,catalog="db_lucas_thiel"
)
public class LltVenda  implements java.io.Serializable {


     private int lltIdVenda;
     private int lltIdCliente;
     private int lltIdVendedor;
     private LltCliente clientes;
     private LltVendedor vendedor;
     private String lltFormaPagamento;
     private String lltModoEnvio;
     private Date lltDataVenda;
     private double lltValorVenda;

    public LltVenda() {
    }

    public LltVenda(int lltIdVenda, int lltIdCliente, int lltIdVendedor, String lltFormaPagamento, String lltModoEnvio, Date lltDataVenda, double lltValorVenda) {
       this.lltIdVenda = lltIdVenda;
       this.lltIdCliente = lltIdCliente;
       this.lltIdVendedor = lltIdVendedor;
       this.lltFormaPagamento = lltFormaPagamento;
       this.lltModoEnvio = lltModoEnvio;
       this.lltDataVenda = lltDataVenda;
       this.lltValorVenda = lltValorVenda;
    }
   
     @Id 

    
    @Column(name="llt_idVenda", unique=true, nullable=false)
    public int getLltIdVenda() {
        return this.lltIdVenda;
    }
    
    public void setLltIdVenda(int lltIdVenda) {
        this.lltIdVenda = lltIdVenda;
    }

    
    @Column(name="llt_idCliente", nullable=false)
    public int getLltIdCliente() {
        return this.lltIdCliente;
    }
    
    public void setLltIdCliente(int lltIdCliente) {
        this.lltIdCliente = lltIdCliente;
    }

    
    @Column(name="llt_idVendedor", nullable=false)
    public int getLltIdVendedor() {
        return this.lltIdVendedor;
    }
    
    public void setLltIdVendedor(int lltIdVendedor) {
        this.lltIdVendedor = lltIdVendedor;
    }

    
    @Column(name="llt_formaPagamento", nullable=false, length=15)
    public String getLltFormaPagamento() {
        return this.lltFormaPagamento;
    }
    
    public void setLltFormaPagamento(String lltFormaPagamento) {
        this.lltFormaPagamento = lltFormaPagamento;
    }

    
    @Column(name="llt_modoEnvio", nullable=false, length=30)
    public String getLltModoEnvio() {
        return this.lltModoEnvio;
    }
    
    public void setLltModoEnvio(String lltModoEnvio) {
        this.lltModoEnvio = lltModoEnvio;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "llt_idCliente", insertable = false, updatable = false)
public LltCliente getLltCliente() {
    return this.clientes;
}
    
    public void setLltCliente(LltCliente clientes) {
        this.clientes = clientes;
    }

    @ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "llt_idVendedor", insertable = false, updatable = false)
public LltVendedor getLltVendedor() {
    return this.vendedor;
}

    
    public void setLltVendedor(LltVendedor vendedor) {
        this.vendedor = vendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="llt_dataVenda", nullable=false, length=10)
    public Date getLltDataVenda() {
        return this.lltDataVenda;
    }
    
    public void setLltDataVenda(Date lltDataVenda) {
        this.lltDataVenda = lltDataVenda;
    }

    
    @Column(name="llt_valorVenda", nullable=false, precision=10)
    public double getLltValorVenda() {
        return this.lltValorVenda;
    }
    
    public void setLltValorVenda(double lltValorVenda) {
        this.lltValorVenda = lltValorVenda;
    }




}


